// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnpa-hvBSmCz3eOF86Mf5vZEA4uX0ZoUo',
    appId: '1:333694457806:web:4189bfb7f673d2606afd9f',
    messagingSenderId: '333694457806',
    projectId: 'budgetbites-1c321',
    authDomain: 'budgetbites-1c321.firebaseapp.com',
    storageBucket: 'budgetbites-1c321.appspot.com',
    measurementId: 'G-KJTXJFJMBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9vrznYdMbeU0Q1dWbQfwINK9BqPqJLcc',
    appId: '1:333694457806:android:8a446bb652b2299a6afd9f',
    messagingSenderId: '333694457806',
    projectId: 'budgetbites-1c321',
    storageBucket: 'budgetbites-1c321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV8sFW78pRTNAA7uYPRYdPEhROEdVE6M0',
    appId: '1:333694457806:ios:38010ee77587a8026afd9f',
    messagingSenderId: '333694457806',
    projectId: 'budgetbites-1c321',
    storageBucket: 'budgetbites-1c321.appspot.com',
    iosBundleId: 'com.example.budgetBites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV8sFW78pRTNAA7uYPRYdPEhROEdVE6M0',
    appId: '1:333694457806:ios:e71f4262a3b6adb06afd9f',
    messagingSenderId: '333694457806',
    projectId: 'budgetbites-1c321',
    storageBucket: 'budgetbites-1c321.appspot.com',
    iosBundleId: 'com.example.budgetBites.RunnerTests',
  );
}
